device: cuda
dataset:
  name: CIFAR10
  dataset_dir: ''
  image_size: 224
  n_channels: 3
model:
  type: cifar
  name: resnet_two_tree_HL
  init_mode: kaiming_fan_out
  resnet_two_tree_HL:
    depth: 50
    initial_channels: 64
    block_type: bottleneck
    n_blocks: [3, 4, 6, 3]
train:
  seed: 0
  precision: O0
  batch_size: 32
  subdivision: 1
  optimizer: sgd
  base_lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 1e-4
  output_dir: experiments/cifar10/LSFL/resnet_two_tree_HL/exp00
  log_period: 10
  checkpoint_period: 10
  val_ratio: 0.0
  use_test_as_val: True
  use_tensorboard: True
  distributed: False
  dataloader:
    num_workers: 8
    drop_last: True
    pin_memory: False
validation:
  batch_size: 128
  dataloader:
    num_workers: 8
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 90
  type: multistep
  milestones: [30, 60]
  lr_decay: 0.1
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
  random_crop:
    padding: 4
    fill: 0
    padding_mode: constant
  random_horizontal_flip:
    prob: 0.5
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
tensorboard:
  train_images: False
  val_images: False
  model_params: False